# Generated by Django 2.1.5 on 2024-01-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20240131_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
